### ISSUE TITLE
Problem: Need demo feature goals for FOSDEM 2015

### ISSUE THREAD

**Issue by jemc** [edgenet/hydra#43]
Solution: Start ironing out scope of features in a discussion here, soon enough to have enough time to implement `libhydra` in C (and/or other languages) as well as a QML app for android that uses `libhydra` to do something interesting/stimulating for FOSDEM-goers.
https://fosdem.org/2015/

**Comment by jemc** [comment]
Closing this issue, as I'd hope we know what features we're doing by now ;)

**Comment by hintjens** [comment]
Feature #1: get something working :-)
