### ISSUE TITLE
Problem: No logo image.

### ISSUE THREAD

**Issue by jemc** [edgenet/hydra#49]
I don't want to get too fancy with the graphics for the first iteration of the QML application for this FOSDEM 2015, as we don't have much time to prepare, but it would be nice to at least have a basic logo for a splash screen and to demonstrate how image posts look and behave in Hydra.

I'm not very graphically-inclined, so I'm hoping someone else will step up and want to give us a logo image.  Ideally, it would go well with the android "Holo Dark" theme (see http://developer.android.com/design/style/themes.html).  Something minimal and vector-based sounds nice to me, but I'll leave the graphic design up to those who are good at it.

We should avoid using content that would bring us undue copyright encumberment - if you do graphics work you probably know what this entails better than I do.

**Comment by hintjens** [comment]
I'll make a mock logo. What image sizes do we need? I assume we need the
logo in several sizes.

**Comment by jemc** [comment]
It can even be as simple as the ZeroMQ `∅` logo.  I like the idea of it being minimal.

An SVG would be ideal, as QML can render SVGs natively and if we end up needing a rasterized image like a JPEG or similar we could can always pre-render it at any size we need.

If this is not possible, maybe render in 8 or so stages with the max size at roughly 1000x1000 and the minimum size at roughly 64x64.
