### ISSUE TITLE
Compilation error on OS/X

### ISSUE THREAD

**Issue by lukebond** [edgenet/hydra#64]
In preparation for 0MQ training at FOSDEM I'm installing the hydra stack. I get the following error during `make check` for hydra after following the installation instructions in the main README:

```
lbond@Lukes-MacBook-Air /Users/lbond/Development/hydra (master)
$ make check
Making check in doc
make[1]: Nothing to be done for `check'.
  CC       src/src_libhydra_la-hydra.lo
src/hydra.c:55:36: error: comparison of constant -1 with expression of type 'mode_t' (aka 'unsigned short') is always false
      [-Werror,-Wtautological-constant-out-of-range-compare]
    if (zsys_file_mode (directory) == -1)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~
1 error generated.
make[1]: *** [src/src_libhydra_la-hydra.lo] Error 1
make: *** [check-recursive] Error 1
```

Is there an extra step required to build on OS/X or is it not currently possible?

**Comment by jemc** [comment]
This may be an issue upstream in czmq, as `zsys_file_mode` very explicitly can return `-1`.
https://github.com/zeromq/czmq/blob/master/src/zsys.c#L566

This probably needs to be looked at more closely in czmq, but for time being, if you wish to just get up and running, see if you can adjust your `CFLAGS` at configure time to exclude `-Wtautological-constant-out-of-range-compare`.

**Comment by hintjens** [comment]
I've fixed it on CZMQ master, pull request waiting to be merged: https://github.com/zeromq/czmq/pull/903
