### ISSUE TITLE
Problem: hydra_fetch does not fetch local files

### ISSUE THREAD

**Issue by jemc** [edgenet/hydra#70]
We need a way for the application to receive existing posts we already have if we intend to view them.  I don't know if we want to expand the scope of `hydra_fetch` to also fetch local posts as well as remote ones, or if we need to add another method for fetching local posts into the application for viewing.

**Comment by hintjens** [comment]
Ah, yes. How about exposing the ledger object? Then you load the ledger,
and fetch whatever posts you like from it.

On Wed, Jan 28, 2015 at 11:01 AM, Joe Eli McIlvain <notifications@github.com

**Comment by hintjens** [comment]
I'll make the API model for hydra_ledger.

**Comment by jemc** [comment]
Now I'll just have to make the hydra app fetch all ledger posts on startup before fetching from the network.
