### ISSUE TITLE
Problem: No API for opening a `hydra_ledger` in the right directory.

### ISSUE THREAD

**Issue by jemc** [edgenet/hydra#74]
Looking at the `hydra_ledger` class, it looks like the directory must be set via `zsys_dir_change`, which is not exposed in the wrappable modelled API.  We need some way to make sure the ledger gets opened in the right directory.

Ideally, I'd like to not have to specify the directory again if I've already given it to my instance of the `hydra` class in `hydra_new`.

Proposed solution: Add the `hydra_make_ledger` method that will create and return a "fresh" `hydra_ledger` that was `hydra_ledger_load`ed in the right directory.  This way, all I have to do is get a ledger from the main hydra instance, fetch all the posts from it, and destroy the ledger.

If this sounds right, I don't mind adding it myself.

**Comment by hintjens** [comment]
Sounds good. I'm not convinced that switching directory is safe (it affects
the whole process) so we may have to switch to using absolute paths at some
point.

On Wed, Jan 28, 2015 at 10:03 PM, Joe Eli McIlvain <notifications@github.com

**Comment by jemc** [comment]
Yeah I was wondering about that zdir usage across threads  ;-)
I haven't done much work with files in CZMQ, so I hadn't seen that usage yet.

Anyway, I'll implement it as described and hopefully that will bring us up to the API surface we need to actually get the app doing actual hydrish things.

**Comment by hintjens** [comment]
Ack

**Comment by jemc** [comment]
Hm, this turns out to be not so easy to do right when the paths are relative.
I'm going to leave this feature out for now and only use absolute paths in the app.
